name: build

on:
  push:
    branches: [ master, v1 ]
  pull_request:
    branches: [ master, v1 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Versions below 2.7 and 3.5 are not supported by GitHub
        python-version: ["2.7", "3.5", "3.6", "3.7",  "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with Mypy
      if: 'contains(fromJson(''["3.6", "3.7", "3.8", "3.9", "3.10"]''), matrix.python-version)'
      run: |
        poetry run mypy --allow-untyped-globals --ignore-missing-imports term2048
    - name: Test build
      run: |
        poetry build
    - name: Run Tests
      run: |
        poetry run python tests/pty_run.py
